### ISSUE TITLE
Preflight "tags: always" conflicts with --tags option

### ISSUE THREAD

**Issue by akx** [cloudalchemy/ansible-grafana#101]
Hi hi!

I have a playbook that configures a full Prometheus + Grafana stack on a node via task dependencies, with each dependency tagged, e.g. `tags: prometheus`, `tags: grafana`.

The problem here is that if I just want to run Prometheus reconfiguration (`--tags=prometheus`), bits and pieces of Grafana stuff still gets run, since `tags: always` overrides command line `--tags`.

This is compounded by the fact that I have, as best practices dictate, the Grafana password stored as an Ansible vaulted variable. This means "Fail when grafana admin password isn't set" fails even if I don't want to touch the Grafana configuration at all, if I haven't somehow entered the vault password.

**Comment by rlex** [comment]
Somewhat simular issue here. Is there any reason why preflight is set as always run?

**Comment by paulfantom** [comment]
There is no reason. It is a bug and needs to be fixed.

**Comment by krzyzakp** [comment]
I created PR #109 which shoul solve this issue, it passed checks (finally - needed to find, that pytest 3.10.0 is broken). @paulfantom could you take a look on it?

**Comment by paulfantom** [comment]
Closing since #109 should solve this issue
