### ISSUE TITLE
Prometheus dashboard cannot be imported - Invalid alert data. Cannot save dashboard

### ISSUE THREAD

**Issue by DrHashi** [cloudalchemy/ansible-grafana#111]
configuration:

`grafana_dashboards:
   - dashboard_id: 5984 # Linux Alert nodes
     revision_id: 1
     datasource: prometheus
   - dashboard_id: 2121 # RabbitMQ
     revision_id: 1
     datasource: prometheus
   - dashboard_id: 617 # AWS EC2
     revision_id: 3
     datasource: cloudwatch`

Error: 

`ok: [10.1.1.26] => (item=/tmp/dashboards/617.json)
failed: [10.1.1.26] (item=/tmp/dashboards/alerts-linux-nodes_rev1.json) => {"changed": false, "connection": "close", "content": "{\"message\":\"Invalid alert data. Cannot save dashboard\"}", "content_length": "55", "content_type": "application/json", "date": "Tue, 13 Nov 2018 15:40:45 GMT", "item": "/tmp/dashboards/alerts-linux-nodes_rev1.json", "json": {"message": "Invalid alert data. Cannot save dashboard"}, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "http://0.0.0.0:3000/api/dashboards/db"}
failed: [10.1.1.26] (item=/tmp/dashboards/2121.json) => {"changed": false, "connection": "close", "content": "{\"message\":\"Invalid alert data. Cannot save dashboard\"}", "content_length": "55", "content_type": "application/json", "date": "Tue, 13 Nov 2018 15:40:46 GMT", "item": "/tmp/dashboards/2121.json", "json": {"message": "Invalid alert data. Cannot save dashboard"}, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "http://0.0.0.0:3000/api/dashboards/db"}
ok: [10.1.1.26] => (item=/tmp/dashboards/aws-ec2_rev3.json)
failed: [10.1.1.26] (item=/tmp/dashboards/rabbitmq-metrics_rev1.json) => {"changed": false, "connection": "close", "content": "{\"message\":\"Invalid alert data. Cannot save dashboard\"}", "content_length": "55", "content_type": "application/json", "date": "Tue, 13 Nov 2018 15:40:47 GMT", "item": "/tmp/dashboards/rabbitmq-metrics_rev1.json", "json": {"message": "Invalid alert data. Cannot save dashboard"}, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "http://0.0.0.0:3000/api/dashboards/db"}
failed: [10.1.1.26] (item=/tmp/dashboards/5984.json) => {"changed": false, "connection": "close", "content": "{\"message\":\"Invalid alert data. Cannot save dashboard\"}", "content_length": "55", "content_type": "application/json", "date": "Tue, 13 Nov 2018 15:40:47 GMT", "item": "/tmp/dashboards/5984.json", "json": {"message": "Invalid alert data. Cannot save dashboard"}, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "http://0.0.0.0:3000/api/dashboards/db"}`

grafana log

`t=2018-11-13T10:40:45-0500 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Invalid alert data. Cannot save dashboard"
t=2018-11-13T10:40:45-0500 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db status=500 remote_addr=127.0.0.1 time_ms=42 size=55 referer=
t=2018-11-13T10:40:46-0500 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Invalid alert data. Cannot save dashboard"
t=2018-11-13T10:40:46-0500 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db status=500 remote_addr=127.0.0.1 time_ms=39 size=55 referer=
t=2018-11-13T10:40:47-0500 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Invalid alert data. Cannot save dashboard"
t=2018-11-13T10:40:47-0500 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db status=500 remote_addr=127.0.0.1 time_ms=36 size=55 referer=
t=2018-11-13T10:40:47-0500 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Invalid alert data. Cannot save dashboard"
t=2018-11-13T10:40:47-0500 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db status=500 remote_addr=127.0.0.1 time_ms=35 size=55 referer=`

**Comment by paulfantom** [comment]
This is a grafana error. Similar problems were seen in previous grafana versions, like here: https://community.grafana.com/t/invalid-alert-data-cannot-save-dashboard/6090/13
