### ISSUE TITLE
Alert deployment ? 

### ISSUE THREAD

**Issue by michael-will** [cloudalchemy/ansible-grafana#114]
Using ansible to deploy our grafana server I was happy to find the datasource and dashboard provisioning mechanisms to work very well by creating yml/json files. I assign the dashboards into a folder 'provisioned' so its easy for our users to understand what dashboards are provided and which ones they have created on their own without them getting overwritten. 

Next item is the alerts system. Is there work in progress to support that in a similar fashion or am I better off using sqlite to write the definitions into the alerts table directly?

**Comment by paulfantom** [comment]
From what I know grafana doesn't have a way to provision alerts and API calls aren't the best way to do it.
