### ISSUE TITLE
flush_handlers task does not support when conditional

### ISSUE THREAD

**Issue by DmitryRomanenko** [cloudalchemy/ansible-grafana#118]
```
TASK [cloudalchemy.grafana : Install plugins] *********************************************************************************************************************************************************************
 [WARNING]: flush_handlers task does not support when conditional
```

The problem is:

I have a task A, that flushes handlers in role B.  
Role A is executed before grafana, role B is after it.  
And in first execution the script failes because `flush_handlers task does not support when conditional` and is executed every time.

**Comment by paulfantom** [comment]
I don't see where is the problem. The only place we are using `flush_handlers` is https://github.com/cloudalchemy/ansible-grafana/blob/bb9eedca9330fadff17b79590345b2cfe5e5460f/tasks/main.yml#L40-L47

and this task doesn't use any conditional statements. If there is other role affecting role execution, then I don't know how this can be solved apart from spliting into separate playbooks. There is nothing else we can do on role level.
