### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-grafana#12]
Role could create additional users if it is possible (possibility should be checked in `tasks/preflight.yml`).

This probably can be accomplished via [grafana API](http://docs.grafana.org/http_api/user)

**Comment by rockandska** [comment]
Just to let you know i've start to work on adding users/organisations management and will try to push a PR ASAP.
But adding this, mean adding it to many functionality ( dashboards, datasources, etc... ) and require more works i had imagined :smile:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
