### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by sylvainOL** [cloudalchemy/ansible-grafana#130]
Hello,
this playbook doesn't support proxy support as `package` module is launched without `environment: "{{ grafana_environment }}"`.

it's thus doesn't work :(

**Comment by paulfantom** [comment]
Could you create a PR?

**Comment by sylvainOL** [comment]
I will test this afternoon.
if proxy is configured on the apt side (I assume it's the same with yum), this works but I think it should be good to have a consistent behavior.
