### ISSUE TITLE
WTF bug with grafana_dashboards_dir == dashboards

### ISSUE THREAD

**Issue by amarao** [cloudalchemy/ansible-grafana#136]
If `grafana_dashboards_dir` is set to `dashboards` fileglob finds `roles/cloudalchemy.grafana/files/dashboards` and ignores all other folders in the playbook directory.

It cause some big WTF as `grafana_dashboards_dir=myboards` will loads dashboards from it (f.e. `myproject/dashboards` (with the role inside `myproject/roles/cloudalchemy.grafana`)), and `grafana_dashboards_dir=dashboards` won't find anything  because it finds `myproject/roles/cloudalchemy.grafana/files/dashboards` and stops there instead of looking into `myproject/dashboards`.

I think it should be noted in documentation  (defaults/main.yaml), or, better, to be fixed work with 'dashboards' name.

**Comment by paulfantom** [comment]
Could you test what would happen if we remove `cloudalchemy.grafana/files/dashboards` directory from this role?

**Comment by amarao** [comment]
Hello. If I do `rm -r cloudalchemy.grafana/files/dashboards` it allows to use my own 'dashboards' playbook directory (as expected).

I checked the second scenario: no `cloudalchemy.grafana/files/dashboards`, no `dashboards in role`,  `grafana_dashboards_dir` is not modified (default value from role defaults), it works fine, but with warning:

```
TASK [cloudalchemy.grafana : Set the correct data source name in the dashboard] *************************************************************************************************************
 [WARNING]: Unable to find 'dashboards' in expected paths (use -vvvvv to see paths)
```

**Comment by paulfantom** [comment]
Then I think we should remove `files` directory. Could you create a PR? :)
