### ISSUE TITLE
On upgrade from Grafana 6.0.0 -> 6.0.2 users & dashboards not provisioned are lost

### ISSUE THREAD

**Issue by dovreshef** [cloudalchemy/ansible-grafana#144]
As stated in the title: On upgrade from Grafana 6.0.0 -> 6.0.2 users & dashboards not provisioned are lost. How can I upgrade versions but still keep users & their dashboards?

(The users are set using Google oauth, if it matters).

**Comment by paulfantom** [comment]
This is very strange as we are not manipulating grafana database directly so all entries from 6.0.0 should be there in 6.0.2.

Did you set `grafana_use_provisioning: false` or used default setting of `grafana_use_provisioning: true`?

**Comment by dovreshef** [comment]
I used the default, which I assume is true. I did not know it would get rid of the dashboards not provisioned. Or the users..

**Comment by paulfantom** [comment]
As for dashboards, we by default synchronize them. Look here: https://github.com/cloudalchemy/ansible-grafana/blob/master/defaults/main.yml#L8-L9

As for users, we have zero mechanisms to remove them. We don't even have any mechanism to add them.

It looks to me like you encountered something not directly related to this ansible role.

**Comment by dovreshef** [comment]
Ok. Thanks. Will close and check with Grafana.
