### ISSUE TITLE
Package is always updated to latest version

### ISSUE THREAD

**Issue by matthiasmay** [cloudalchemy/ansible-grafana#153]
I would prefer, that the grafana package (on Debian) is not updated to the latest version but kept at the currently installed version.

Eg. by setting grafana_version: present.
However, this would need a modification in vars/debian.yml where grafana_package is set:
`grafana_package: "grafana{{ (grafana_version != 'latest') | ternary('=' ~ grafana_version, '') }}"`

Or did I miss how to achieve that behaviour?

**Comment by paulfantom** [comment]
If you want to use specific version, you need to specify [`grafana_version` variable](https://github.com/cloudalchemy/ansible-grafana/blob/master/defaults/main.yml#L2).

By design there is no option to keep currently installed version after installing `latest` one.

**Comment by matthiasmay** [comment]
Thanks for your quick reply.

Is this a final decision or would you be open to a suggestion to change this/pull request?

My use case is that I run ansible --check every night to verify that there are no changes but the grafana rule frequently shows a change when the package is updated. I'd prefer to to the package upgrade manually.

**Comment by paulfantom** [comment]
This is a final decision.

All roles in @cloudalchemy are meant to be used in automated systems with "GitOps" in mind. Basically state of a system should be reflected by what is in a configuration repository and it should allow to quickly rebuild system by using that repository. What you are proposing is creating a break in such workflow as it needs manual actions performed on a system.
