### ISSUE TITLE
update of grafana_security.admin_password

### ISSUE THREAD

**Issue by gajowi** [cloudalchemy/ansible-grafana#158]
I find if I update my inventory admin_password, grafana.ini gets updated and the service is restarted, but the new password is not active (the old one still applies). I suppose the active setting is actually in the sqlite db.

Is this my mistake, by design or an oversight?

**Comment by paulfantom** [comment]
This is by grafana design. Source: https://grafana.com/docs/installation/configuration/#admin-password
