### ISSUE TITLE
Support for installing plugins

### ISSUE THREAD

**Issue by thescouser89** [cloudalchemy/ansible-grafana#159]
I'd be nice to be able to specify a list of plugins that we want installed in the grafana server

**Comment by thescouser89** [comment]
Very very nice! :)

**Comment by thescouser89** [comment]
Let me know if you want me to keep it open until it's documented? Otherwise I think you've answered my question! :) Thank you!

**Comment by paulfantom** [comment]
It would be good to document it. Could you take care of that? :)

**Comment by thescouser89** [comment]
:+1:
