### ISSUE TITLE
Unable to use with Ubuntu 18.04.

### ISSUE THREAD

**Issue by kevingimbel** [cloudalchemy/ansible-grafana#191]
This playbook does  not work on Ubuntu 18.04 because the package  `gnupg2` is no longer available but is a dependency here https://github.com/cloudalchemy/ansible-grafana/blob/db9b5fb57a47ce8849c674094813892350028b1e/vars/debian.yml#L3-L8

According to [this comment on AskUbuntu](https://askubuntu.com/questions/748057/how-do-i-install-gnupg-2-0#comment1713081_748059) `gnupg` is `gnupg2` in Ubuntu 18.04, so for Ubuntu 18.04 (and possibly newer versions) `gnupg` could be installed. 

I changed the value in my local copy of the playbook and was able to install Grafana on Ubuntu 18.04.

**Comment by paulfantom** [comment]
Installation is continuously [tested on ubuntu 18.04](https://github.com/cloudalchemy/ansible-grafana/blob/master/molecule/default/molecule.yml#L9-L14) and `gnupg2` is still available in [ubuntu 18.04 repositories](https://launchpad.net/ubuntu/+source/gnupg2/2.2.4-1ubuntu1.2), so I wonder where is the problem?

**Comment by da-snap** [comment]
I have the same error. System is a Ubuntu 18.04.3 LTS
My error output is:
```
TASK [cloudalchemy.grafana : Install dependencies] ****************************************************************************************************************************************************************
FAILED - RETRYING: Install dependencies (5 retries left).
FAILED - RETRYING: Install dependencies (4 retries left).
FAILED - RETRYING: Install dependencies (3 retries left).
FAILED - RETRYING: Install dependencies (2 retries left).
FAILED - RETRYING: Install dependencies (1 retries left).
fatal: [server.name]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'gnupg2' is available"}
```
When I try to install gnupg2 directly on the server I get:
```
$ sudo apt-get install gnupg2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gnupg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gpgv gpgsm gnupg-l10n gnupg dirmngr

E: Package 'gnupg2' has no installation candidate
```

**Comment by cm5089** [comment]
The fix is to edit /etc/apt/sources.list to change `...bionic main` to `bionic main universe` before running apt-get update and apt update. I have limited experience with Ubuntu package management so I can't speak to a reason for this - I just happened to solve this in passing the other day.

**Comment by paulfantom** [comment]
@cm5089 great find! However this list is not managed by ansible-grafana role so could you add info about necessary enablement of `universe` apt repo in ubuntu 18.04 and higher to [README.md Requirements](https://github.com/cloudalchemy/ansible-grafana#requirements) section?

**Comment by nlsdfnbch** [comment]
I believe we ran into the same issue on another role - the easiest fix was to run
```
- apt: { update_cache: yes }
```
in the `pre_tasks` section of the play executing the role, iirc.

**Comment by paulfantom** [comment]
For compatibility reasons, role is not using `apt` module directly (`package` is used) and I would prefer to stay it this way.

**Comment by paulfantom** [comment]
This is already done in https://github.com/cloudalchemy/ansible-grafana/blob/master/tasks/install.yml#L4-L6
