### ISSUE TITLE
Installation fails due to missing package libfontconfig on Ubuntu 18.04

### ISSUE THREAD

**Issue by obitech** [cloudalchemy/ansible-grafana#200]
**What happened?**

This role fails with a recent Ubuntu 18.04 system:

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ uname -r
4.15.0-76-generic
```

This is because `libfontconfig` has changed to `libfontconfig1`.
Running an `apt update` manually on the host before executing the role solves it.

Weirdly enough the role succeeds on a recent Debian system, even though though
it still requires `libfontconfig1`.

```
$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ uname -r
4.19.0-6-amd64
```

```
$ apt install libfontconfig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libfontconfig

# running apt update

$ apt install libfontconfig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1
```

**Did you expect to see some different?**

It should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Execute the role on a fresh Ubuntu 18.04 installation as target

**Environment**

* Role version:

```
0.16.1
```

* Ansible version information:

```
ansible 2.9.4
  config file = None
  configured module search path = ['/home/aknipping/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/aknipping/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

* Variables:

```
nothing relevant
```

* Ansible playbook execution Logs:

```
TASK [./roles/cloudalchemy.grafana : Install dependencies] ********************************************************************************
FAILED - RETRYING: Install dependencies (5 retries left).
FAILED - RETRYING: Install dependencies (4 retries left).
FAILED - RETRYING: Install dependencies (3 retries left).
FAILED - RETRYING: Install dependencies (2 retries left).
FAILED - RETRYING: Install dependencies (1 retries left).
fatal: [10.36.22.140]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'libfontconfig' is available"}
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Ansible role doesn't depend on that package. It looks like direct grafana dependency and should be reported to grafana itself.

**Comment by obitech** [comment]
That's correct but even the Grafana docs state `libfontconfig1` should be used: https://grafana.com/docs/grafana/latest/installation/debian/#install-deb-package

**Comment by paulfantom** [comment]
Looks like debian can handle deprecating packages in a graceful way without causing problems.

Could you test if https://github.com/cloudalchemy/ansible-grafana/pull/201 fixes it?

**Comment by obitech** [comment]
Left a comment on your PR
