### ISSUE TITLE
Playlist provisioning

### ISSUE THREAD

**Issue by alanmcg** [cloudalchemy/ansible-grafana#203]
**What is missing?**

Ability to provision playlists in a similar fashion to dashboards

**Why do we need it?**

Creating multiple grafana installations for different environments should allow automation of this feature to remove manual work

**Anything else we need to know?**:

Playlists can be provisioned via API as per docs:
https://grafana.com/docs/grafana/latest/http_api/playlist/

**Comment by paulfantom** [comment]
This is something that should be done with ansible module, so please forward such request to https://github.com/ansible-collections/grafana. We are not going to provide hacky ways of doing this with `uri/url` modules.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
