### ISSUE TITLE
Preflight check for curl is missing

### ISSUE THREAD

**Issue by funkyfuture** [cloudalchemy/ansible-grafana#204]
**What is missing?**

a preflight-check for `curl` on the deployer machine

**Why do we need it?**

users are pointed to the cause of a failure explicitly

**Is it important?**

not really, it's just more convenient and iirc that check is included in other roles that you provide. thank your for your efforts.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
