### ISSUE TITLE
cast grafana_port to int before comparing it to 1024

### ISSUE THREAD

**Issue by kapouer** [cloudalchemy/ansible-grafana#212]
**What happened?**
```
The conditional check 'grafana_port <= 1024' failed.
The error was: Unexpected templating type error occurred on ({% if grafana_port <= 1024 %} True {% else %} False {% endif %}): '<=' not supported between instances of 'str' and 'int'
The error appears to be in '/home/dev/.ansible/roles/cloudalchemy.grafana/tasks/preflight.yml': line 80
```

**Did you expect to see some different?**
grafana_port should be settable using jinja templates.

**How to reproduce it (as minimally and precisely as possible)**:
- set_fact: myport=9999
...
  grafana_port: "{{ myport }}"

**Environment**
debian/sid

* Role version:
0.16.2

* Ansible version information:
2.9.6

* What else ? *

I tried to use the `| int` filter but it won't work. "Jinja always output strings".

**Comment by paulfantom** [comment]
Probably needs altering this line: https://github.com/cloudalchemy/ansible-grafana/blob/master/templates/grafana.ini.j2#L20 Could you create a PR and test it?

**Comment by kapouer** [comment]
No that won't work: the check is in a task, not in a template.

**Comment by kapouer** [comment]
But let me PR this another way
