### ISSUE TITLE
support for Azure AD OAuth2 authentication

### ISSUE THREAD

**Issue by ashish15feb** [cloudalchemy/ansible-grafana#220]
**What is missing?**
Azure AD OAuth2 authentication

**Why do we need it?**
This is available in the latest Grafana release but not supported in this role. The current role supports ldap only.

**Comment by paulfantom** [comment]
This is supported with:
```
grafana_auth:
  azuread:
	<<parameters for Azure AD>>
```

Where parameters are from https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana
