### ISSUE TITLE
Permit setting of grafana_package prefix without using extra-vars

### ISSUE THREAD

**Issue by kunickiaj** [cloudalchemy/ansible-grafana#228]
It's not currently possible to set grafana_package outside of using extra-vars because it's set by role vars.

If I want to install the grafana-enterprise package I currently must override the yum repo template, but then set grafana_package using extra vars. It would make it simpler for users to install the enterprise binaries if there were a flag in the normal vars for this.

If this seems like a reasonable ask, I'm happy to open a PR.

* Role version:

    `0.17.0`

* Ansible version information:

    `ansible 2.8.13`

**Comment by paulfantom** [comment]
Seems good to me, please open a PR.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
