### ISSUE TITLE
datasource task produces invalid provisioning yaml

### ISSUE THREAD

**Issue by jurim76** [cloudalchemy/ansible-grafana#236]
**What happened?**
Invalid /etc/grafana/provisioning/datasources/ansible.yml provisioning yaml
`
apiVersion: 1
deleteDatasources: []
datasources:
- database: influxdb
  json_data:
    httpMode: GET
  name: InfluxDB01
  secure_json_data:
    password: ****
  type: influxdb
  url: http://influxdb01:8086
  user: influxdb_user
- json_data:
    password: ****
    username: zabbix_user
  name: Zabbix
  secure_json_data:
    password: ****
  type: alexanderzobnin-zabbix-datasource
  url: https://zbx/api_jsonrpc.php
`
**Did you expect to see some different?**

Correct provisioning yaml expected

apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    url: "http://influxdb01:8086"
    database: "influxdb""
    user: "influxdb_user"
    json_data:
      httpMode: "GET"
    secure_json_data:
      password: "****"
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    url: "https://zbx/api_jsonrpc.php"
    jsonData:
      username: "zabbix_user"
      password: "****"

**How to reproduce it (as minimally and precisely as possible)**:

Enable provisioning and define datasource with json_data in inventory

grafana_use_provisioning: yes
grafana_datasources:
  - name: "InfluxDB"
    type: "influxdb"
    url: "http://influxdb01:8086"
    user: "{{ influxdb_username }}"
    json_data:
      httpMode: "GET"
    secure_json_data:
      password: "{{ influxdb_password }}"
    database: "{{ influxdb_database }}"
  - name: "Zabbix"
    type: "alexanderzobnin-zabbix-datasource"
    url: "https://{{ zabbix_server }}/api_jsonrpc.php"
    json_data:
      username: "{{ zabbix_username }}"
      password: "{{ zabbix_password }}"

*
*Environment**
* Role version:

  0.17.0

* Ansible version information:

   ansible 2.9.13
  config file = /home/jurim/git/sysadmin/ansible/ansible_local.cfg
  configured module search path = ['/home/jurim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jurim/.local/lib/python3.8/site-packages/ansible
  executable location = /home/jurim/.local/bin/ansible
  python version = 3.8.5 (default, Aug 17 2020, 22:05:15) [GCC 9.3.0]

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
