### ISSUE TITLE
Convert grafana.ini to not use Jinja2

### ISSUE THREAD

**Issue by jhg03a** [cloudalchemy/ansible-grafana#237]
**What is missing?**
As a user, I'd like grafana.ini to use the ini_file module instead of rendering a jinja2 template.

**Why do we need it?**
This allows for users with needs not modeled by this role to use the ini_file module outside the role and preserve idempotency.  Right now, you can do this but it will always trigger changes in both the role and exterior module.  As a bonus, being able to pass in a list of dict to add as unintelligent ini_file additions/modifications would be great too.

**Environment**

* Role version:

    `0.18.0`

* Ansible version information:
```
ansible 2.9.12
config file = None
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.8/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
```

**Anything else we need to know?**:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
