### ISSUE TITLE
grafana_system_user and grafana_system_group are not used

### ISSUE THREAD

**Issue by IyadKandalaft** [cloudalchemy/ansible-grafana#238]
**What happened?**

The grafana-server service fails to start.  Upon review of the logs, I noted that it fails to create the logs directory because of denied permissions.  When I look at the process owner and group, it's grafana for both, which is not what I set grafana_system_user and grafana_system_group to.  Upon review of the repository, the variables are not referenced anywhere.

**Did you expect to see some different?**

Yes, the server process should have the correct ownership as defined by the variables.

**How to reproduce it (as minimally and precisely as possible)**:

Set grafana_system_user and grafana_system_group to something other than the default.  Look at grafana-server service to see that the user has not changed.

**Environment**

* Role version:

b35bab335282442bffdb002c99cd6596f4a77ae8

* Ansible version information:

    `$ ansible --version
ansible 2.9.11
  config file = None
  configured module search path = ['/home/iyad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/iyad/miniconda3/envs/devops/lib/python3.7/site-packages/ansible
  executable location = /home/iyad/miniconda3/envs/devops/bin/ansible
  python version = 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) [GCC 7.3.0]
    `

* Variables:

```
grafana_system_user 
grafana_system_group 
```

* Ansible playbook execution Logs:

```
N/A
```

**Anything else we need to know?**:

No

**Comment by paulfantom** [comment]
You're right, this is a documentation bug as those variables should be deleted from readme. This role is installing deb/rpm package offered by grafana organization and as such cannot influence settings inside said package (like system user or group setting).

**Comment by paulfantom** [comment]
Fixed with https://github.com/cloudalchemy/ansible-grafana/commit/d4634022eaf70891fe81050eeb1d778814f5a934
