### ISSUE TITLE
missing deleteDatasources

### ISSUE THREAD

**Issue by roidelapluie** [cloudalchemy/ansible-grafana#240]
**What is missing?**

In the grafana datasources.yml, it would be great to have access to deleteDatasources.

**Why do we need it?**

To delete grafana data sources with ansible.

**Comment by inkdude** [comment]
+1

don't understand how to delete datasources

**Comment by DavidMorp** [comment]
+ 1

I made a pull request #268

**Comment by jeqo** [comment]
+1

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
