### ISSUE TITLE
Allow disabling check_for_updates

### ISSUE THREAD

**Issue by peschmae** [cloudalchemy/ansible-grafana#253]
**What is missing?**
Right now grafana is always checking for updates, and it would be prefereable if this could be disabled.

**Why do we need it?**
In some environments the host that runs grafana isn't allowed to connect to the outside world, and the update checks, only lead to errors. 

**Environment**

* Role version: 0.18.0

* Ansible version information: irrelevant

**Anything else we need to know?**:

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
