### ISSUE TITLE
Enable setting date_formats in grafana.ini

### ISSUE THREAD

**Issue by arnedc** [cloudalchemy/ansible-grafana#255]
Since grafana v7.2 default date_formats can be set in the grafana.ini file
https://grafana.com/docs/grafana/latest/administration/configuration/?src=grafana_gettingstarted#date_formats

Would be nice if this was enabled via ansible as well.

**Comment by sohnemann** [comment]
This would be much appreciated, as the default setting only really makes sense in North America.
Most countries use DD/MM/YYYY rather than MM/DD/YYYY.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
