### ISSUE TITLE
Allow user to define default_home_dashboard_path

### ISSUE THREAD

**Issue by endersonmaia** [cloudalchemy/ansible-grafana#258]
**What is missing?**

I can't define a provisioned dashboard as the default dashboard for home.

**Why do we need it?**

I need to give access to the default dashboard, so my users don't need to navigate.

See: https://grafana.com/docs/grafana/latest/administration/change-home-dashboard/#set-the-default-dashboard-through-configuration

**Environment**

* Role version: f9b04329fb6416a204001255b67683e62496fc71

* Ansible version information:

    `ansible --version`

```
ansible 2.10.5
  config file = None
  configured module search path = ['/Users/endersonmaia/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.7/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Feb  3 2021, 07:38:02) [Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by endersonmaia** [comment]
a possible "workaround", and maybe there's no need for this issue, would be using `grafana_environment` ansible variable to define `GF_DASHBOARDS_DEFAULT_DASHBOARD_HOME_PATH`

didn't test yet

reference : https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables

**Comment by endersonmaia** [comment]
> a possible "workaround", and maybe there's no need for this issue, would be using `grafana_environment` ansible variable to define `GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH`
> 
> **didn't test yet**
> 
> reference : https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables

that didn't work!

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
