### ISSUE TITLE
Make grafana.ini template configurable

### ISSUE THREAD

**Issue by peschmae** [cloudalchemy/ansible-grafana#262]
**What is missing?**
Currently it's not possible to override the used template for the `grafana.ini` which makes it impossible to set arbitrary config values.

**Why do we need it?**
Some plugins might need additional configurations in the `grafana.ini`, for example if you want to use the [grafana image renderer](https://grafana.com/docs/grafana/latest/administration/image_rendering/)
Currently you would need to add the config in an additional ansible task, breaking idempotency.
Allowing to use a custom template, makes it possible to add any config, without breaking idempotency

**Environment**

* Role version: 0.17.0

* Ansible version information: irrelevant

**Anything else we need to know?**: Partially solves #237

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
