### ISSUE TITLE
feature_toggles config is missing

### ISSUE THREAD

**Issue by ahmadalli** [cloudalchemy/ansible-grafana#275]
**What is missing?**
[feature_toggles](https://grafana.com/docs/grafana/latest/administration/configuration/#feature_toggles) section is missing

**Why do we need it?**

to set `feature_toggles` config

**Environment**

* Role version: `master`

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
