### ISSUE TITLE
search_base_dns is badly formatted in grafana ldap config

### ISSUE THREAD

**Issue by wouterdt** [cloudalchemy/ansible-grafana#284]
**What happened?**
The list gets badly outputted in the ldap.toml , there is an u prepended to the list

ldap.toml
```
search_base_dns = [u'dc=grafana,dc=org]
```
causing grafana to reject the ldap configuration

```
 lvl=eror msg="Failed to obtain the LDAP configuration. Please verify the configuration and try again" logger=context userId=2 orgId=1 uname= error="Failed to load LDAP config file: Near line 10 (last key parsed 'servers.search_base_dns'): expected value but found \"u\" instead" 
```

**Did you expect to see some different?**
there should be no u in the array

**How to reproduce it (as minimally and precisely as possible)**:
set an array of search_base_dns as per the example
https://grafana.com/docs/grafana/latest/auth/ldap/#posix-schema

**Environment**

* Role version:
latest
* Ansible version information:
```
ansible 2.9.17
  config file = /opt/monitoring/ansible/ansible.cfg
  configured module search path = [u'/home/smals-wdt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

* Variables:

```
grafana_ldap:
        search_base_dns:
        - "dc=grafana,dc=org"
```

* Ansible playbook execution Logs:
no errors

**Anything else we need to know?**:
I suppose this is linked to the https://github.com/cloudalchemy/ansible-grafana/issues/283
and the 
```
| to_nice_json
```
present in https://github.com/cloudalchemy/ansible-grafana/blob/master/templates/ldap.toml.j2

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
