### ISSUE TITLE
Add support for file based alert provisioning

### ISSUE THREAD

**Issue by JamesGibo** [cloudalchemy/ansible-grafana#297]
**What is missing?**
Currently `ansible-grafana` does not support alert provisioning as Grafana did not provided an easy method to do this.
From Grafana v9.1.x file based provisioning for alerting has been added and follows the same method as used for dashboards and datasources

https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
