### ISSUE TITLE
grafana GPG key revoked

### ISSUE THREAD

**Issue by anderma** [cloudalchemy/ansible-grafana#300]
With regards to grafana having revoked GPG keys, 

https://grafana.com/blog/2023/01/12/grafana-labs-update-regarding-circleci-security-updates/

The ansible-grafana role fails on the task 'Import Grafana GPG signing key [Debian/Ubuntu]

**Comment by mtraynham** [comment]
Manually resolved by removing the apt-key and apt-repo, then reapplying.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
