### ISSUE TITLE
wait_for timeout not long enough

### ISSUE THREAD

**Issue by anon8675309** [cloudalchemy/ansible-grafana#306]
**What happened?**
When attempting to deploy, the [task to wait for grafana to start](https://github.com/cloudalchemy/ansible-grafana/blob/master/tasks/main.yml#L50) times out.

**Did you expect to see some different?**
Yes, I expect it to wait until grafana starts, or 

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to deploy to any slower computer, one with slow disk I/O will help in reproducing this reliably.

**Environment**
- Both deployer and target are Debian 11 (bullseye) x86_64
- Ansible 2.10.8
- VM deployed by Terraform
- VM deployed to Proxmox

* Role version:
cloudalchemy.grafana version 0.18.0

* Ansible version information:

```
ansible 2.10.8
  config file = /home/production/configs/ansible/hax0rbana/ansible.cfg
  configured module search path = ['/home/production/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

* Variables:

The variable that doesn't exist, but it should is:
```
grafana_timeout: 600
```

The [default is 300](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html#parameter-timeout), but setting it to 600 won't slow anything down in the normal case, and it can be overridden by the user (e.g., if they have even slower servers).

* Ansible playbook execution Logs:

```
TASK [cloudalchemy.grafana : Wait for grafana to start (http/s)] **********************************************************
fatal: [REDACTED.DOMAIN.TLD]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1:300
0"}
```

**Anything else we need to know?**:
I would have submitted a pull request to fix this, but it looks like this repo is no longer maintained.  There hasn't been updated in years, the CI is failing, and there are 37 pull requests of other people trying to improve this library.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
