### ISSUE TITLE
Additional quote is breaking password authentications

### ISSUE THREAD

**Issue by D3N14L** [cloudalchemy/ansible-grafana#32]
According to the Grafana documentation you need to set a password in tripple quotes, if it contains certain characters. Unfortunately this role has an additional closing quote, which causes the quotes to be recognized as part of the password...
https://github.com/cloudalchemy/ansible-grafana/blob/424d400e7786e3c69d98f9d60338b5d30dd23f7a/templates/grafana.ini.j2#L32

**Comment by paulfantom** [comment]
If you can, make PR to this role with a fix from mentioned repository (https://github.com/D3N14L/ansible-grafana/pull/1).

**Comment by D3N14L** [comment]
Sorry - did not notice that I created the PR in my own Repo.
