### ISSUE TITLE
plugins don't work if grafana_data_dir != "/var/lib/grafana"

### ISSUE THREAD

**Issue by ArcolaJasper** [cloudalchemy/ansible-grafana#38]
The plugins get installed to /var/lib/grafana/plugins and then grafana can't find them

https://github.com/cloudalchemy/ansible-grafana/blob/99044dc69bc9d98bfb6945051edaa6e5c1ddd905/tasks/plugins.yml#L9 needs to be something like:

```
command: "grafana-cli  --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ item }}"
```

**Comment by paulfantom** [comment]
We are in the middle of changing how this role handles plugins. There is PR #34 which should solve this issue, could you test if that version works for you?

**Comment by paulfantom** [comment]
@ArcolaJasper it should work now. Thanks for reporting it.
