### ISSUE TITLE
[Question] Dashboard add is done twice

### ISSUE THREAD

**Issue by rockandska** [cloudalchemy/ansible-grafana#68]
Hi,

Not sure if i'm misunderstood the purpose of this but it seems for me to do exactly the same operation twice but once by the api and once by the provisioning capability if the datasource doesn't already exist but will update it only by the provisioning capability if it already exist.

Why not make a choice and only use the api or the provisioning ?

Regards,

https://github.com/cloudalchemy/ansible-grafana/blob/df5655e3b80d85c762f603ed24370dff196bcd48/tasks/datasources.yml#L12-L33

**Comment by paulfantom** [comment]
This is a bug. We should use API for grafana < 5.0 and files for newer versions. Would you like to make a PR? :smile:
