### ISSUE TITLE
Datasource provision does not specify the apiVersion

### ISSUE THREAD

**Issue by g-goessel** [cloudalchemy/ansible-grafana#73]
When we add a new datasource the `jsonData` is not working because of the `apiVersion` is not declared.
The `apiVersion` should be declared on top of the provisioning yaml because otherwise it is considered as an `apiVersion: 0` file an raises this warning : 

> [Deprecated] the datasource provisioning config is outdated. please upgrade

See here for the differences between the versions: [github.com/grafana](https://github.com/grafana/grafana/blob/master/pkg/services/provisioning/datasources/types.go)

It is currently possible to have `jsonData` working by renaming it `json_data` but imho it is better to specify that we are using `apiVersion: 1`.

A PR implementing `apiVersion: 1` is incoming.

**Comment by paulfantom** [comment]
Done in #76
