### ISSUE TITLE
Issue with grafana restart when including one or more datasources

### ISSUE THREAD

**Issue by zonArt** [cloudalchemy/ansible-grafana#85]
Hi,

For some weird reason the copy of the datasource file (/etc/grafana/provisioning/datasources/ansible,yml) is not done with the right ownership and mode doesn't allow all the users to read it, making grafana-server fail to start. Could I kindly ask you to correct that or do you want me to open a PR?

Thanks in advance

**Comment by paulfantom** [comment]
I am currently a little bit busy, so if you could open a PR, that would be helpful.

**Comment by zonArt** [comment]
Here you are #86

**Comment by paulfantom** [comment]
Solved in #86 :tada:
