### ISSUE TITLE
Setup Notification channel

### ISSUE THREAD

**Issue by kagarlickij** [cloudalchemy/ansible-grafana#91]
It looks like feature request, so please tag it if it is,
The idea is to get feature that will set Notification channel(s),
Typically it's done once on server setup, so makes sense on "Ansible stage".

**Comment by paulfantom** [comment]
Can you point to grafana docs saying about this feature?

**Comment by kagarlickij** [comment]
Should be here - http://docs.grafana.org/http_api/alerting/
I'll proceed with it later this week and put API call as soon as find it.

**Comment by paulfantom** [comment]
Isn't this implementing this feature? :
https://github.com/cloudalchemy/ansible-grafana/blob/69d16c5634056481498057f798b8d05f565e70ef/defaults/main.yml#L188-L190
