### ISSUE TITLE
proxy support for yum repo

### ISSUE THREAD

**Issue by fuerer** [cloudalchemy/ansible-grafana#99]
Hi

We are only allowed to access outside world over a webproxy, so it wouldb be great if the template for the repo file would have an option to define the proxy like
proxy=http://host.mydomain.com:proxyport

regards
patrik

**Comment by paulfantom** [comment]
Have you tried using `http_proxy` and `https_proxy` variables?

I don't want to implement features specific to one platform so proxy support should also work on debian and openSUSE.

**Comment by fuerer** [comment]
the problem is that we have internal yum repositories which are not reachable over the webproxy. so for external repos we set the proxy directive in the corresponding repo files.
alternative would be that I can disable the creation of the repo file and use my own.

**Comment by rockandska** [comment]
Too tired to do it now but want to let my thinking for whoever have time before me to do it or discuss it before implementing it:

- create a variable in defaults/main.yml
```
grafana_yum_repo_tpl: grafana.yum.repo.j2
```
- use this variable in the task file "install"
- if the user wants, it could create a personal template inside a directory "templates" at the same level of the playbook with a different name and use it by override the variable ```grafana_yum_repo_tpl```

Already use this kind of workflow in another roles

Regards,

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [grafana-ansible-collection](https://github.com/grafana/grafana-ansible-collection) collection.**
